### ISSUE TITLE
build_macos does not create same binary as Makefile

### ISSUE THREAD

**Issue by dgately** [totalspectrum/loadp2#2]
The loadp2 Makefile creates and executes the following compile command:

    gcc -Wall -O -DMACOSX -o build/loadp2 loadp2.c loadelf.c osint_linux.c

The build_macos file executes the following compile command:

    gcc -Wall -DMACOSX loadp2.c loadelf.c osint_linux.c -o loadp2

Looks like the Makefile variant is building with "-O' optimizations... Should these be the same and is build_macos even needed?

**Comment by totalspectrum** [comment]
build-macos is no longer needed, all the platforms should be built via the Makefile now
